Set JAVA_HOME to point to openjdk
Khan/khan-dotfiles pull request #99
Opened 2024-01-09 22:23 UTC by jwiesebron

## Summary:
Apparently this was previously being set by brew when installing adoptopenjdk11. Symlink openjdk to the system library and and set JAVA_HOME.

Issue: INFRA-9734

## Test plan:
Fully uninstall openjdk and run commands manually. Also run make.

2024-01-09 22:27 UTC, csilvers reviewed
Thank you!

2024-01-09 22:28 UTC, csilvers commented
I'm worried we'll forget to change this, though, when we upgrade to java 14 or whatever comes next.  Is there a way to future-proof this?

2024-01-09 22:32 UTC, jwiesebron commented
I was thinking the same thing. Any objection to me writing to `.profile.khan` from `shared-functions.sh`?

2024-01-09 22:34 UTC, csilvers commented
> I was thinking the same thing. Any objection to me writing to `.profile.khan` from `shared-functions.sh`?

Ooh interesting.  I like that idea.  Then we don't need the os x protection either.

The only thing I'd be careful of is that we don't write the same thing multiple times when running the setup script multiple times.  The goal is to have the script by idempotent.

2024-01-09 23:39 UTC, jwiesebron commented on dotfiles-setup.sh
> +#!/bin/bash
this is copied directly from setup.sh. I did this so I could copy over the dotfiles before running an os-specific install, so [this](https://github.com/Khan/khan-dotfiles/pull/99/files#diff-db35c16b3f04fa41c3d18e63f39627bb1bfb84b52b422ff4f3328ea76e511b66R110) could work.

2024-01-09 23:43 UTC, csilvers requested changes
"Request changes" because you put in a change to .profile.khan that shouldn't be in there.

Don't forget to update the commit message to talk about the refactor and other changes you made, now, too!

2024-01-09 23:43 UTC, csilvers commented on .profile.khan
> +export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
You don't want this as part of the commit!

2024-01-09 23:43 UTC, csilvers commented on shared-functions.sh
> +  if ! brew ls $@ >/dev/null 2>&1; then
```suggestion
  if ! brew ls "$@" >/dev/null 2>&1; then
```
and likewise below.

2024-01-09 23:43 UTC, csilvers commented on shared-functions.sh
> +        if ! grep -q "$JAVA_HOME_STRING" "$PROFILE_FILE"; then
I think a helper function (in shared-functions.sh) might be useful.  That's something like:
```
# $1: the text to add
# $2: the dotfile to add it to, relative to $HOME.
add_to_dotfile() {
    grep -q "$1" "$2" || echo "$1" >> "$2"
}
```

2024-01-09 23:43 UTC, csilvers commented on shared-functions.sh
> +    # Ensure JAVA_HOME is set in ~/.profile.khan
I'd add a TODO here to change other parts of dotfiles to write directly to .profile.khan/etc, as well.

2024-01-09 23:43 UTC, csilvers commented on shared-functions.sh
> +    else
I'd reverse the if and else here, and then you can out-dent all of the else case (because of the `return`).  Just like how we handle errors in go.

2024-01-10 01:04 UTC, csilvers approved these changes
Thanks!  I think this is better, even though it requires a second file.

2024-01-10 01:04 UTC, csilvers commented on shared-functions.sh
> +    PROFILE_FILE="$HOME/.profile-generated.khan"
(Then you can get rid of the $HOME here.)

2024-01-10 01:17 UTC, jwiesebron commented
I'm going to make one more change to delete the generated profile files when running make, but that can be a followup.

2024-01-10 03:59 UTC, csilvers commented on shared-functions.sh
> +    grep -q "$2" "$HOME/$1" || echo "$2" >> "$HOME/$1"
Ooh, it occurs to me that this should be `fgrep`, just to be safe.

2024-01-10 19:44 UTC, merged